### ISSUE TITLE
On ubuntu WSL cargo-watch doesn't seem to trigger when I make changes to main.rs file

### ISSUE THREAD

**Issue by weezy20** [watchexec/cargo-watch#195]

**Comment by passcod** [comment]
Hi Abhishek! I need a lot more information than this to be able to help you:
- OS Version
- WSL Version and distribution
- What you're doing
- What you're expecting
- How you're calling cargo watch
- How you're editing that file (what editor)
- Some kind of logs

Otherwise, I'll go ahead and close this issue as unactionable in a few days. Thanks!
